
package View;

import Controller.AdminController;

/**
 *
 * @author Evandro
 */
public class Adm extends javax.swing.JFrame {
    
    final private AdminController controller;
    /**
     * Creates new form Funcoes
     */
    public Adm() {
        initComponents();
        
        controller = new AdminController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        painel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cadastroProfessor = new javax.swing.JMenuItem();
        cadastroAluno = new javax.swing.JMenuItem();
        matricula = new javax.swing.JMenuItem();
        semestre = new javax.swing.JMenuItem();
        notas = new javax.swing.JMenu();
        disciplina = new javax.swing.JMenuItem();
        horario = new javax.swing.JMenuItem();
        Notas = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setBackground(new java.awt.Color(0, 102, 255));
        Titulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Titulo.setText("Sistema Acadêmico");
        Titulo.setOpaque(true);
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 43));

        painel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icone/painel.jpg"))); // NOI18N
        getContentPane().add(painel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 39, 800, 510));

        jMenu1.setText("Administrador");

        cadastroProfessor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cadastroProfessor.setText("Cadastrar Professor");
        cadastroProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroProfessorActionPerformed(evt);
            }
        });
        jMenu1.add(cadastroProfessor);

        cadastroAluno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cadastroAluno.setText("Cadastrar Aluno");
        cadastroAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroAlunoActionPerformed(evt);
            }
        });
        jMenu1.add(cadastroAluno);

        matricula.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        matricula.setText("Disciplinas");
        matricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculaActionPerformed(evt);
            }
        });
        jMenu1.add(matricula);

        semestre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        semestre.setText("Semestre ");
        semestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semestreActionPerformed(evt);
            }
        });
        jMenu1.add(semestre);

        jMenuBar1.add(jMenu1);

        notas.setText("Professor");

        disciplina.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        disciplina.setText("Disciplina");
        disciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disciplinaActionPerformed(evt);
            }
        });
        notas.add(disciplina);

        horario.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        horario.setText("Horário");
        notas.add(horario);

        Notas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Notas.setText("Notas");
        notas.add(Notas);

        jMenuBar1.add(notas);

        jMenu3.setText("Mais");

        sair.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        jMenu3.add(sair);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void disciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disciplinaActionPerformed

    private void cadastroAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroAlunoActionPerformed
        controller.telaCadastroAluno();
    }//GEN-LAST:event_cadastroAlunoActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    private void cadastroProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroProfessorActionPerformed
        controller.telaCadastroProfessor();
    }//GEN-LAST:event_cadastroProfessorActionPerformed

    private void semestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semestreActionPerformed
        controller.telaSemestre();
    }//GEN-LAST:event_semestreActionPerformed

    private void matriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculaActionPerformed
        controller.telaDisciplinas();
    }//GEN-LAST:event_matriculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Notas;
    private javax.swing.JLabel Titulo;
    private javax.swing.JMenuItem cadastroAluno;
    private javax.swing.JMenuItem cadastroProfessor;
    private javax.swing.JMenuItem disciplina;
    private javax.swing.JMenuItem horario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem matricula;
    private javax.swing.JMenu notas;
    private javax.swing.JLabel painel;
    private javax.swing.JMenuItem sair;
    private javax.swing.JMenuItem semestre;
    // End of variables declaration//GEN-END:variables
}
