/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author Evandro
 */
public class EscolherDisc extends javax.swing.JFrame {

    /**
     * Creates new form EscolherDisc
     */
    public EscolherDisc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        labelTitulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        disciplina1 = new javax.swing.JCheckBox();
        disciplina2 = new javax.swing.JCheckBox();
        disciplina3 = new javax.swing.JCheckBox();
        disciplina4 = new javax.swing.JCheckBox();
        disciplina5 = new javax.swing.JCheckBox();
        disciplina6 = new javax.swing.JCheckBox();
        disciplina7 = new javax.swing.JCheckBox();
        disciplina8 = new javax.swing.JCheckBox();
        botãoConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        labelTitulo.setBackground(new java.awt.Color(0, 102, 255));
        labelTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Escolher Disciplina");
        labelTitulo.setOpaque(true);

        disciplina1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        disciplina1.setForeground(new java.awt.Color(255, 255, 255));
        disciplina1.setText("Disciplina 1");
        disciplina1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disciplina1ActionPerformed(evt);
            }
        });

        disciplina2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        disciplina2.setForeground(new java.awt.Color(255, 255, 255));
        disciplina2.setText("Disciplina 2");

        disciplina3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        disciplina3.setForeground(new java.awt.Color(255, 255, 255));
        disciplina3.setText("Disciplina 3");

        disciplina4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        disciplina4.setForeground(new java.awt.Color(255, 255, 255));
        disciplina4.setText("Disciplina 4");

        disciplina5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        disciplina5.setForeground(new java.awt.Color(255, 255, 255));
        disciplina5.setText("Disciplina 5");

        disciplina6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        disciplina6.setForeground(new java.awt.Color(255, 255, 255));
        disciplina6.setText("Disciplina 6");

        disciplina7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        disciplina7.setForeground(new java.awt.Color(255, 255, 255));
        disciplina7.setText("Disciplina 7");

        disciplina8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        disciplina8.setForeground(new java.awt.Color(255, 255, 255));
        disciplina8.setText("Disciplina 8");

        botãoConfirmar.setBackground(new java.awt.Color(0, 102, 255));
        botãoConfirmar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botãoConfirmar.setText("Confirmar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(disciplina1)
                    .addComponent(disciplina2)
                    .addComponent(disciplina3)
                    .addComponent(disciplina4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(disciplina5)
                            .addComponent(disciplina6)
                            .addComponent(disciplina7)
                            .addComponent(disciplina8))
                        .addGap(178, 178, 178))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botãoConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(disciplina1)
                        .addGap(39, 39, 39)
                        .addComponent(disciplina2)
                        .addGap(39, 39, 39)
                        .addComponent(disciplina3)
                        .addGap(39, 39, 39)
                        .addComponent(disciplina4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(disciplina5)
                        .addGap(39, 39, 39)
                        .addComponent(disciplina6)
                        .addGap(39, 39, 39)
                        .addComponent(disciplina7)
                        .addGap(39, 39, 39)
                        .addComponent(disciplina8)))
                .addGap(17, 17, 17)
                .addComponent(botãoConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 848, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void disciplina1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disciplina1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_disciplina1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EscolherDisc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EscolherDisc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EscolherDisc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EscolherDisc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscolherDisc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botãoConfirmar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox disciplina1;
    private javax.swing.JCheckBox disciplina2;
    private javax.swing.JCheckBox disciplina3;
    private javax.swing.JCheckBox disciplina4;
    private javax.swing.JCheckBox disciplina5;
    private javax.swing.JCheckBox disciplina6;
    private javax.swing.JCheckBox disciplina7;
    private javax.swing.JCheckBox disciplina8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
